# Sobrescritas para desenvolvimento local
environment: development

debug:
  enabled: true
  log_level: debug
  show_dev_panel: true
  features:
    api_trace: true
    mock_stripe: true
    mock_avalara: true
    skip_email_send: true
    expose_config_endpoint: true
    seed_demo_data: true

features:
  marketplace_plugins: true  # testar marketplace em dev
